permissions:
    contents: write

name: Create Release Branch

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Name of the release branch to create'
        required: true

jobs:
  create_release_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout develio branch
        uses: actions/checkout@v3
        with:
          ref: develop

      - name: Create new release branch and push to remote
        run: |
          git config user.name "GitHub Action"
          git checkout -b ${{ github.event.inputs.branch_name }}
          git push origin ${{ github.event.inputs.branch_name }}