name: example-workflow

on:
  push:
    branches:
      - master

jobs:
  my-context:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "HELLO! $MY_ACTOR"
        env:
          MY_ACTION: ${{ github.action }}
          MY_ACTOR: ${{ github.actor }}



